{{ if and (index .Values "modules" "text2vec-huggingface" "enabled") (index .Values "modules" "text2vec-huggingface" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaviate.fullname" . }}-huggingface
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-huggingface" "apiKey" | b64enc }}
{{ end }}
