{{ if and (index .Values "modules" "text2vec-morph" "enabled") (index .Values "modules" "text2vec-morph" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaviate.fullname" . }}-morph
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-morph" "apiKey" | b64enc }}
{{ end }}
