{{- $backup := index .Values "backups" "s3" -}}
{{ if and (index $backup "enabled") (index $backup "secrets") }}
{{- if or (index $backup "secrets" "AWS_ACCESS_KEY_ID") (index $backup "secrets" "AWS_SECRET_ACCESS_KEY") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaviate.fullname" . }}-backup-s3
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if index $backup "secrets" "AWS_ACCESS_KEY_ID" }}
  AWS_ACCESS_KEY_ID: {{ index $backup "secrets" "AWS_ACCESS_KEY_ID" | b64enc }}
  {{- end }}
  {{- if index $backup "secrets" "AWS_SECRET_ACCESS_KEY" }}
  AWS_SECRET_ACCESS_KEY: {{ index $backup "secrets" "AWS_SECRET_ACCESS_KEY" | b64enc }}
  {{- end }}
{{- end }}
{{ end }}
