{{- $backup := index .Values "backups" "gcs" -}}
{{ if and (index $backup "enabled") (index $backup "secrets") }}
{{- if index $backup "secrets" "GOOGLE_APPLICATION_CREDENTIALS" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaviate.fullname" . }}-backup-gcs
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
type: Opaque
data:
  GOOGLE_APPLICATION_CREDENTIALS: {{ index $backup "secrets" "GOOGLE_APPLICATION_CREDENTIALS" | b64enc }}
{{- end }}
{{ end }}
