{{- $podDisruptionBudget := index .Values "podDisruptionBudgets" "weaviate" -}}
{{- if index $podDisruptionBudget "enabled" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "weaviate.fullname" . }}
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "weaviate.selectorLabels" . | nindent 6 }}
      app: {{ include "weaviate.name" . }}
  {{- toYaml $podDisruptionBudget.spec | nindent 2 }}
{{- end -}}
