apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaviate.fullname" . }}-headless
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "weaviate.selectorLabels" . | nindent 4 }}
    app: {{ include "weaviate.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.env.CLUSTER_GOSSIP_BIND_PORT }}
  publishNotReadyAddresses: true
